import type { CalcSection } from "./types";

export type ToolMeta = {
  id: string;
  section: CalcSection;
  title: string;
  version: string;
  published: string;
  reviewedAt: string;
  source: string;
  population: string;
  formula: string;
  limitations: string;
  officialUrl?: string;
  licenseNote?: string;
  active: boolean;
};

export const CALC_TOOLS: ToolMeta[] = [
  {
    id: "ckd_epi_cr_2021",
    section: "rim",
    title: "CKD-EPI 2021 — Creatinina",
    version: "2021",
    published: "Inker et al. NEJM 2021",
    reviewedAt: "2026-09-25",
    source: "CKD-EPI creatinina 2021, sem fator raça",
    population: "Adultos. Exige creatinina (mg/dL), idade e sexo.",
    formula: "142 × min(Cr/κ,1)^α × max(Cr/κ,1)^−1,2 × 0,9938^idade × 1,012 [se mulher]; κ 0,7/0,9; α −0,241/−0,302",
    limitations: "Estimativa da TFG indexada à SC. Não substitui clearance medido.",
    officialUrl: "https://www.kidney.org/professionals/kdoqi/gfr_calculator",
    active: true,
  },
  {
    id: "ckd_epi_cys_2021",
    section: "rim",
    title: "CKD-EPI 2021 — Cistatina C",
    version: "2021",
    published: "Inker et al. NEJM 2021",
    reviewedAt: "2026-09-25",
    source: "CKD-EPI cistatina C 2021",
    population: "Adultos com cistatina C (mg/L), idade e sexo.",
    formula: "133 × min(Cys/0,8,1)^−0,499 × max(Cys/0,8,1)^−1,328 × 0,996^idade × 0,932 [se mulher]",
    limitations: "Cistatina sofre influência de inflamação e tireoide.",
    active: true,
  },
  {
    id: "ckd_epi_cr_cys_2021",
    section: "rim",
    title: "CKD-EPI 2021 — Creatinina + Cistatina C",
    version: "2021",
    published: "Inker et al. NEJM 2021",
    reviewedAt: "2026-09-25",
    source: "CKD-EPI creatinina-cistatina C 2021",
    population: "Adultos com creatinina e cistatina C na mesma avaliação (ou datas manuais explícitas).",
    formula: "135 × min(Cr/κ,1)^α × max(Cr/κ,1)^−0,544 × min(Cys/0,8,1)^−0,323 × max(Cys/0,8,1)^−0,778 × 0,9961^idade × 0,963 [se mulher]",
    limitations: "Não mistura datas distantes sem o médico aceitar.",
    active: true,
  },
  {
    id: "kdigo_ga",
    section: "rim",
    title: "Classificação KDIGO G + A",
    version: "KDIGO CKD 2024 (categorias G/A estáveis)",
    published: "KDIGO Clinical Practice Guideline for the Evaluation and Management of CKD",
    reviewedAt: "2026-09-25",
    source: "Categorias G (TFGe) e A (RAC/UACR em mg/g)",
    population: "Quando houver TFGe e/ou RAC. Não infere albuminúria ausente.",
    formula: "G1 ≥90; G2 60–89; G3a 45–59; G3b 30–44; G4 15–29; G5 <15. A1 <30; A2 30–300; A3 >300 mg/g",
    limitations: "Categoria A exige RAC. Proteinúria de fita não substitui ACR.",
    active: true,
  },
  {
    id: "cockcroft_gault",
    section: "rim",
    title: "Cockcroft-Gault (CrCl)",
    version: "1976",
    published: "Cockcroft DW, Gault MH. Nephron 1976",
    reviewedAt: "2026-09-25",
    source: "Clearance de creatinina estimado — não é CKD-EPI",
    population: "Adultos com peso, idade, sexo e creatinina. Usado quando a referência de dose exigir CrCl.",
    formula: "CrCl (mL/min) = [(140 − idade) × peso (kg) × (0,85 se mulher)] / (72 × Cr mg/dL)",
    limitations: "Não indexado à SC. Em obesidade/desnutrição o peso usado altera o resultado.",
    active: true,
  },
  {
    id: "kfre_4var",
    section: "rim",
    title: "KFRE 4 variáveis",
    version: "4-var, calibração não-norte-americana, Tangri 2016",
    published: "Tangri et al. JAMA 2011; 2016;315:164-174",
    reviewedAt: "2026-09-25",
    source: "Risco de falência renal tratada (diálise/transplante) em 2 e 5 anos",
    population: "DRC com TFGe < 60 mL/min/1,73 m², não em TRS. Adultos. ACR obrigatória.",
    formula: "PI = −0,2201·(idade/10−7,036)+0,2467·(homem−0,5642)−0,5567·(TFGe/5−7,222)+0,4510·(ln(ACR mg/mmol)−5,137); risco = 1−S0^exp(PI); S0(2a)=0,9832; S0(5a)=0,9365; ACR mg/mmol = RAC mg/g ÷ 8,84",
    limitations: "Não prediz morte. Calibração não-NA (Brasil). Não usar em TRS/G5D.",
    officialUrl: "https://kidneyfailurerisk.com/",
    active: true,
  },
  {
    id: "prevent",
    section: "cardiovascular",
    title: "PREVENT (AHA)",
    version: "AHA PREVENT 2023/2024 — aplicabilidade",
    published: "Khan et al. Circulation 2024;149:430-449",
    reviewedAt: "2026-09-25",
    source: "AHA PREVENT™ — risco de CVD em 10 anos (equações oficiais da AHA)",
    population: "30–79 anos, sem CVD conhecido. EUA/população de derivação. Não extrapolar.",
    formula: "Equações sex-específicas publicadas no suplemento de Khan 2024. O Meu Rim verifica população e dados; o número sai da ferramenta oficial da AHA até incorporação autorizada dos coeficientes.",
    limitations: "Não usar se CVD prévio, idade fora de 30–79 ou dados incompletos.",
    officialUrl: "https://professional.heart.org/en/guidelines-and-statements/prevent-calculator",
    licenseNote: "PREVENT™ é marca da American Heart Association. Coeficientes oficiais não foram reproduzidos neste módulo.",
    active: true,
  },
  {
    id: "renal_dose",
    section: "medicamentos",
    title: "Ajuste de dose renal",
    version: "2026-09 catálogo Meu Rim",
    published: "Bulas/ANVISA e referências listadas por fármaco",
    reviewedAt: "2026-09-25",
    source: "Orientação cadastrada por medicamento — o médico decide",
    population: "Quando houver função renal (CKD-EPI ou Cockcroft-Gault, conforme a ficha).",
    formula: "Consulta à ficha do fármaco + função renal atual. Nunca altera a prescrição.",
    limitations: "Catálogo inicial, não substitui bula nem farmacêutico clínico.",
    active: true,
  },
  {
    id: "polypharmacy",
    section: "medicamentos",
    title: "Polifarmácia",
    version: "1.0",
    published: "Contagem de medicamentos ativos do prontuário",
    reviewedAt: "2026-09-25",
    source: "Lista de medicamentos em uso",
    population: "Qualquer paciente com lista de medicações.",
    formula: "Conta itens ativos. Não usa regra “≥5 = retirar”.",
    limitations: "Sinaliza revisão. Não suspende nada.",
    active: true,
  },
  {
    id: "geriatric_med_review",
    section: "geriatria",
    title: "Revisão geriátrica de medicamentos",
    version: "regras Meu Rim 2026-09 (estrutura STOPP/START)",
    published: "Regras próprias com fonte por alerta — não é o instrumento STOPP/START oficial",
    reviewedAt: "2026-09-25",
    source: "Revisão de inapropriados/omissões comuns em idoso com DRC",
    population: "Idosos (≥60) ou quando o médico pedir revisão. STOPP/START oficial exige licença.",
    formula: "Regras cadastradas (AINEs + DRC, metformina + TFGe baixa, duplicidade, etc.).",
    limitations: "Não reproduz o texto oficial STOPP/START. Resultado = revisar, nunca suspender.",
    licenseNote: "STOPP/START é instrumento publicado com direitos. Aqui só há estrutura e regras próprias.",
    active: true,
  },
  {
    id: "urr",
    section: "hemodialise",
    title: "URR",
    version: "clássico",
    published: "Redução percentual de ureia",
    reviewedAt: "2026-09-25",
    source: "Mesma fórmula do módulo de hemodiálise do Meu Rim",
    population: "Sessão de HD com ureia pré e pós.",
    formula: "URR = (ureia pré − ureia pós) / ureia pré × 100",
    limitations: "Não calcula se pós ≥ pré ou se faltar valor.",
    active: true,
  },
  {
    id: "ktv_daugirdas",
    section: "hemodialise",
    title: "Kt/V (Daugirdas)",
    version: "Daugirdas (sem UF se peso/UF ausentes)",
    published: "Daugirdas JT",
    reviewedAt: "2026-09-25",
    source: "Mesma função do módulo de hemodiálise",
    population: "HD com ureia pré, pós e tempo da sessão.",
    formula: "−ln(R − 0,008·t) [+ (4 − 3,5·R)·(UF/peso) se UF e peso]",
    limitations: "Sem tempo ou ureias válidas, não calcula.",
    active: true,
  },
  {
    id: "anion_gap",
    section: "eletrolitos",
    title: "Ânion gap",
    version: "clássico",
    published: "Na − (Cl + HCO3)",
    reviewedAt: "2026-09-25",
    source: "Bioquímica clínica",
    population: "Com sódio, cloro e bicarbonato.",
    formula: "AG = Na − (Cl + HCO3). Corrigido = AG + 2,5 × (4 − albumina)",
    limitations: "Unidades em mEq/L. Sem albumina, não corrige.",
    active: true,
  },
  {
    id: "delta_gap",
    section: "eletrolitos",
    title: "Delta gap / delta ratio",
    version: "clássico",
    published: "Distúrbio ácido-base misto",
    reviewedAt: "2026-09-25",
    source: "AG excesso / HCO3 déficit",
    population: "Quando AG e HCO3 estão disponíveis e AG está elevado.",
    formula: "ΔAG = AG − 12; ΔHCO3 = 24 − HCO3; razão = ΔAG / ΔHCO3",
    limitations: "Não aplica se AG normal. Referências 12 e 24 podem variar.",
    active: true,
  },
  {
    id: "na_corrected_glucose",
    section: "eletrolitos",
    title: "Sódio corrigido pela glicose",
    version: "Hillier / fator 1,6",
    published: "Correção clássica por hiperglicemia",
    reviewedAt: "2026-09-25",
    source: "Na corr = Na + 1,6 × ((glicose − 100)/100)",
    population: "Glicose > 100 mg/dL e sódio medido.",
    formula: "Na + 1,6 × ((glicose mg/dL − 100) / 100)",
    limitations: "Fator 1,6 é uma convenção; outros usam 2,4 em glicose muito alta.",
    active: true,
  },
  {
    id: "osm_calculated",
    section: "eletrolitos",
    title: "Osmolaridade calculada e gap",
    version: "2·Na + glicose/18 + ureia/6",
    published: "Fórmula com ureia em mg/dL (laboratório BR)",
    reviewedAt: "2026-09-25",
    source: "Osm calc; gap só com osm medida",
    population: "Na + glicose + ureia. Gap exige osmolaridade medida.",
    formula: "Osm = 2·Na + glicose/18 + ureia/6. Gap = osm medida − calculada",
    limitations: "Ureia BR em mg/dL (≈ BUN × 2,14). Sem osm medida, não há gap.",
    active: true,
  },
  {
    id: "ca_corrected",
    section: "eletrolitos",
    title: "Cálcio corrigido",
    version: "clássico",
    published: "Payne",
    reviewedAt: "2026-09-25",
    source: "Ca + 0,8 × (4 − albumina)",
    population: "Cálcio total (mg/dL) e albumina (g/dL).",
    formula: "Ca corr = Ca + 0,8 × (4 − albumina)",
    limitations: "Não substitui cálcio iônico.",
    active: true,
  },
  {
    id: "fena",
    section: "eletrolitos",
    title: "FENa",
    version: "clássico",
    published: "Fração de excreção de sódio",
    reviewedAt: "2026-09-25",
    source: "(UNa/PNa) ÷ (UCr/PCr) × 100",
    population: "Na e Cr plasmáticos e urinários.",
    formula: "FENa (%) = (UNa × PCr) / (PNa × UCr) × 100",
    limitations: "Diuréticos invalidam a interpretação clássica.",
    active: true,
  },
  {
    id: "feureia",
    section: "eletrolitos",
    title: "FEUreia",
    version: "clássico",
    published: "Fração de excreção de ureia",
    reviewedAt: "2026-09-25",
    source: "(Uureia/Pureia) ÷ (UCr/PCr) × 100",
    population: "Ureia e Cr plasmáticos e urinários.",
    formula: "FEUreia (%) = (Uureia × PCr) / (Pureia × UCr) × 100",
    limitations: "Útil quando há diurético; ainda assim interpretação clínica.",
    active: true,
  },
  {
    id: "cfs",
    section: "geriatria",
    title: "Clinical Frailty Scale (CFS)",
    version: "registro de escore 1–9",
    published: "Rockwood et al.",
    reviewedAt: "2026-09-25",
    source: "Avaliação clínica do estado funcional basal — não se calcula pela idade",
    population: "Avaliação presencial/funcional pelo profissional.",
    formula: "Escore atribuído pelo médico após avaliação. Sem cálculo automático.",
    limitations: "Não inferir fragilidade só por idade ou diagnósticos.",
    officialUrl: "https://www.dal.ca/sites/gmr/our-tools/clinical-frailty-scale.html",
    licenseNote: "A escala oficial tem condições de uso. O Meu Rim registra o escore e aponta o instrumento oficial — não reproduz textos/imagens da CFS.",
    active: true,
  },
  {
    id: "function_basic",
    section: "geriatria",
    title: "Funcionalidade básica",
    version: "1.0",
    published: "Campos clínicos do Meu Rim",
    reviewedAt: "2026-09-25",
    source: "ABVD, AIVD, mobilidade, cuidador — registro, não escala licenciada",
    population: "Qualquer paciente; especialmente idosos.",
    formula: "Registro estruturado. Não gera nota única de mortalidade.",
    limitations: "Não é prognóstico automático.",
    active: true,
  },
  {
    id: "geriatric_prognosis",
    section: "geriatria",
    title: "Prognóstico geriátrico",
    version: "arquitetura 1.0",
    published: "Índices só com população de validação (ex. ePrognosis)",
    reviewedAt: "2026-09-25",
    source: "Catálogo vazio até cada índice ser cadastrado com licença e coeficientes",
    population: "Definida por índice. Sem índice cadastrado, não calcula.",
    formula: "Pergunta prévia: esta ferramenta é apropriada para este paciente?",
    limitations: "Não há calculadora universal de mortalidade.",
    active: true,
  },
  {
    id: "spict",
    section: "suporte",
    title: "SPICT — indicadores de suporte",
    version: "registro de indicadores",
    published: "Supportive and Palliative Care Indicators Tool",
    reviewedAt: "2026-09-25",
    source: "Identificar necessidade de avaliação de cuidados de suporte — não sobrevida",
    population: "Doença crônica avançada / deterioração. Avaliação clínica.",
    formula: "Indicadores confirmados pelo médico. Sem estimativa de meses de vida.",
    limitations: "Nunca rotular “paciente é paliativo” nem prognóstico em meses.",
    officialUrl: "https://www.spict.org.uk/",
    licenseNote: "O instrumento oficial SPICT tem condições de reprodução. Aqui há registro de indicadores e link oficial.",
    active: true,
  },
  {
    id: "necpal",
    section: "suporte",
    title: "NECPAL",
    version: "registro de necessidade de avaliação",
    published: "NECPAL CCOMS-ICO",
    reviewedAt: "2026-09-25",
    source: "Identificar possíveis necessidades paliativas/suporte em doença crônica avançada",
    population: "Doença crônica avançada, inclusive DRC grave. Avaliação clínica.",
    formula: "Pergunta surpresa + indicadores confirmados. Não estima sobrevida.",
    limitations: "Não serve para recusar diálise nem limitar tratamento automaticamente.",
    licenseNote: "Não reproduzimos o instrumento oficial. Registro + link quando disponível.",
    active: true,
  },
  {
    id: "pps",
    section: "suporte",
    title: "PPS — registro",
    version: "registro de escore",
    published: "Palliative Performance Scale",
    reviewedAt: "2026-09-25",
    source: "Escore informado pelo médico. Sem tabela PPSv2 neste app.",
    population: "Quando clinicamente apropriado e o médico atribuir o escore.",
    formula: "Registro 0–100. Tendência = escores anteriores.",
    limitations: "PPSv2 tem requisitos de licença. Não incorporamos o algoritmo oficial.",
    licenseNote: "Aguardando autorização para conteúdo integral do PPSv2.",
    active: true,
  },
];

export function getTool(id: string): ToolMeta | undefined {
  return CALC_TOOLS.find((t) => t.id === id);
}

export const SECTION_LABEL: Record<CalcSection, string> = {
  rim: "Rim",
  cardiovascular: "Cardiovascular",
  medicamentos: "Medicamentos",
  geriatria: "Geriatria",
  suporte: "Cuidados de suporte",
  hemodialise: "Hemodiálise",
  eletrolitos: "Eletrólitos e ácido-base",
};
