export const DOCUMENT_AUDIT_EVENTS = [
  "DOCUMENT_CREATED",
  "DOCUMENT_UPDATED",
  "DOCUMENT_LOCKED",
  "DOCUMENT_VERSION_CREATED",
  "CONSENT_PRESENTED",
  "CONSENT_ACCEPTED",
  "CONSENT_DECLINED",
  "SIGNATURE_STARTED",
  "DIGITAL_SIGNATURE_COMPLETED",
  "DIGITAL_SIGNATURE_VALIDATED",
  "DIGITAL_SIGNATURE_FAILED",
  "MANUAL_SIGNATURE_SELECTED",
  "DOCUMENT_PRINTED",
  "DOCUMENT_DOWNLOADED_FOR_SIGNATURE",
  "MANUAL_SIGNED_DOCUMENT_UPLOADED",
  "DOCUMENT_RELEASED",
  "DOCUMENT_SHARED",
  "DOCUMENT_DOWNLOADED",
  "DOCUMENT_SUPERSEDED",
  "DOCUMENT_CANCELLED",
] as const;

export type DocumentAuditEvent = (typeof DOCUMENT_AUDIT_EVENTS)[number];
