import type { DocumentDefinition, SignatureMethodKind } from "./types";

const BOTH: SignatureMethodKind[] = ["DIGITAL", "MANUAL"];
const DIGITAL_PREF: SignatureMethodKind[] = ["DIGITAL", "MANUAL", "EXTERNAL_OFFICIAL_FLOW"];
const OFFICIAL_BOTH: SignatureMethodKind[] = ["DIGITAL", "MANUAL"];

function def(partial: DocumentDefinition): DocumentDefinition {
  return partial;
}

/**
 * DocumentRegistry — fonte única dos tipos de documento do Meu Rim.
 * Não duplicar esta lista em telas. Entradas apontam para código/rotas já existentes.
 * Desativar (`active: false`) é a forma de aposentar — nunca apagar silenciosamente.
 */
export const DOCUMENT_REGISTRY: readonly DocumentDefinition[] = [
  def({
    id: "receita",
    name: "Receita",
    category: "receita",
    description: "Prescrição médica no papel timbrado do médico.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: DIGITAL_PREF,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx", "src/lib/document-engine.ts"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "exame",
    name: "Pedido de exames",
    category: "exame",
    description: "Solicitação de exames laboratoriais ou de imagem.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "relatorio",
    name: "Relatório médico",
    category: "relatorio",
    description: "Relatório clínico no prontuário.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: DIGITAL_PREF,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx", "src/lib/complementary-docs.ts"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "laudo",
    name: "Laudo",
    category: "laudo",
    description: "Laudo médico.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "atestado",
    name: "Atestado",
    category: "atestado",
    description: "Atestado médico.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "encaminhamento",
    name: "Encaminhamento",
    category: "encaminhamento",
    description: "Encaminhamento a outro serviço.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "declaracao",
    name: "Declaração",
    category: "declaracao",
    description: "Declaração médica.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "parecer",
    name: "Parecer",
    category: "parecer",
    description: "Parecer médico.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "orientacao",
    name: "Orientações",
    category: "orientacao",
    description: "Orientações ao paciente.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx"],
    integrityRoutes: ["/api/documents/generate"],
  }),
  def({
    id: "livre",
    name: "Documento livre",
    category: "livre",
    description: "Documento avulso no compositor.",
    active: true,
    official: false,
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: true,
    canSendToPatient: true,
    integrityPaths: ["src/app/medicos/paciente/[email]/documento/page.tsx", "src/app/medicos/documentos/page.tsx"],
    integrityRoutes: ["/api/documents/generate", "/api/documents/avulso"],
  }),
  def({
    id: "lme",
    name: "LME oficial SESAB/CEAF",
    category: "lme",
    description: "Laudo de Medicamentos Especializados — formulário oficial da SESAB, sem redesenho.",
    active: true,
    official: true,
    authority: "SESAB/BA",
    source: "public/forms/lme-oficial.pdf",
    templateVersion: "oficial",
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: OFFICIAL_BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: false,
    canSendToPatient: true,
    integrityPaths: [
      "src/components/LmeWizard.tsx",
      "src/app/lme/[id]/page.tsx",
      "src/lib/lme-store.ts",
      "public/forms/lme-oficial.pdf",
    ],
    integrityRoutes: ["/api/doctor/lme", "/api/lme/[id]", "/api/ceaf/official"],
  }),
  def({
    id: "ter",
    name: "Termo de esclarecimento e responsabilidade (TER)",
    category: "ter",
    description: "Páginas oficiais do pacote SESAB/CEAF nefrologia. Não é redesenhado.",
    active: true,
    official: true,
    authority: "SESAB/BA",
    source: "public/forms/ceaf-sesab-nefrologia.pdf",
    requiresDoctorSignature: true,
    requiresPatientSignature: true,
    requiresGuardianSignature: false,
    allowedSignatureMethods: OFFICIAL_BOTH,
    applicableProtocols: [
      "anemia_drc_alfaepoetina",
      "anemia_drc_ferro",
      "dmo_drc",
      "sindrome_nefrotica_pediatrica",
      "les",
    ],
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: false,
    canSendEmail: false,
    canSendToPatient: true,
    integrityPaths: [
      "src/components/OfficialCeafDocs.tsx",
      "src/lib/ceaf-documents.ts",
      "src/lib/ceaf-official-pdf.ts",
      "public/forms/ceaf-sesab-nefrologia.pdf",
    ],
    integrityRoutes: ["/api/ceaf/official"],
  }),
  def({
    id: "formulario_oficial",
    name: "Formulário oficial de acesso CEAF",
    category: "formulario_oficial",
    description: "Formulário médico oficial do protocolo SESAB.",
    active: true,
    official: true,
    authority: "SESAB/BA",
    source: "public/forms/ceaf-sesab-nefrologia.pdf",
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: OFFICIAL_BOTH,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: false,
    canSendEmail: false,
    canSendToPatient: false,
    integrityPaths: ["src/components/OfficialCeafDocs.tsx", "src/lib/ceaf-documents.ts"],
    integrityRoutes: ["/api/ceaf/official"],
  }),
  def({
    id: "residencia_terceiro",
    name: "Declaração de residência de terceiro",
    category: "formulario_oficial",
    description: "Declaração complementar do pacote CEAF.",
    active: true,
    official: true,
    authority: "SESAB/BA",
    requiresDoctorSignature: false,
    requiresPatientSignature: true,
    requiresGuardianSignature: false,
    allowedSignatureMethods: ["MANUAL"],
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: false,
    canSendEmail: false,
    canSendToPatient: false,
    integrityPaths: ["src/lib/ceaf-documents.ts"],
    integrityRoutes: ["/api/ceaf/official"],
  }),
  def({
    id: "consentimento_teleconsulta",
    name: "Termo de consentimento para teleconsulta",
    category: "consentimento",
    description: "Consentimento assistencial da plataforma. Versão versionada; aceite explícito.",
    active: true,
    official: false,
    authority: "Meu Rim / CFM",
    templateVersion: "1.0",
    requiresDoctorSignature: false,
    requiresPatientSignature: true,
    requiresGuardianSignature: false,
    allowedSignatureMethods: ["MANUAL"],
    canPrint: true,
    canDownload: true,
    canShare: false,
    canSendWhatsapp: false,
    canSendEmail: false,
    canSendToPatient: false,
    integrityPaths: ["src/lib/consent.ts", "src/components/ConsentGate.tsx"],
    integrityRoutes: ["/api/consent/documents", "/api/consent/accept"],
  }),
  def({
    id: "privacidade_lgpd",
    name: "Política de privacidade (LGPD)",
    category: "consentimento",
    description: "Tratamento de dados. Independente da pesquisa científica.",
    active: true,
    official: false,
    authority: "Meu Rim",
    templateVersion: "1.0",
    requiresDoctorSignature: false,
    requiresPatientSignature: true,
    requiresGuardianSignature: false,
    allowedSignatureMethods: ["MANUAL"],
    canPrint: true,
    canDownload: true,
    canShare: false,
    canSendWhatsapp: false,
    canSendEmail: false,
    canSendToPatient: false,
    integrityPaths: ["src/lib/consent.ts", "src/lib/consent-store.ts"],
    integrityRoutes: ["/api/consent/documents"],
  }),
  def({
    id: "termos_uso",
    name: "Termos de uso",
    category: "consentimento",
    description: "Termos da plataforma.",
    active: true,
    official: false,
    authority: "Meu Rim",
    templateVersion: "1.0",
    requiresDoctorSignature: false,
    requiresPatientSignature: true,
    requiresGuardianSignature: false,
    allowedSignatureMethods: ["MANUAL"],
    canPrint: true,
    canDownload: true,
    canShare: false,
    canSendWhatsapp: false,
    canSendEmail: false,
    canSendToPatient: false,
    integrityPaths: ["src/lib/consent.ts"],
    integrityRoutes: ["/api/consent/documents"],
  }),
  def({
    id: "pesquisa_cientifica",
    name: "Consentimento de pesquisa científica",
    category: "consentimento",
    description: "Pesquisa é independente da assistência. Recusar não bloqueia atendimento.",
    active: true,
    official: false,
    authority: "CEP/CONEP",
    requiresDoctorSignature: false,
    requiresPatientSignature: true,
    requiresGuardianSignature: false,
    allowedSignatureMethods: ["MANUAL"],
    canPrint: true,
    canDownload: true,
    canShare: false,
    canSendWhatsapp: false,
    canSendEmail: false,
    canSendToPatient: false,
    integrityPaths: ["src/lib/research-governance-store.ts"],
    integrityRoutes: ["/api/pesquisa/studies"],
  }),
  def({
    id: "assinatura_digital",
    name: "Assinatura digital ICP-Brasil (VIDaaS)",
    category: "administrativo",
    description: "Fluxo de assinatura dos PDFs gerados no Meu Rim. Sem API inventada.",
    active: true,
    official: true,
    authority: "ICP-Brasil / Valid VIDaaS / Assinador gov.br",
    requiresDoctorSignature: true,
    requiresPatientSignature: false,
    requiresGuardianSignature: false,
    allowedSignatureMethods: DIGITAL_PREF,
    canPrint: true,
    canDownload: true,
    canShare: true,
    canSendWhatsapp: true,
    canSendEmail: false,
    canSendToPatient: true,
    integrityPaths: [
      "src/components/SignDocumentFlow.tsx",
      "src/lib/digital-signature/providers.ts",
      "src/lib/digital-signature/attach-signed.ts",
      "src/lib/signature-links.ts",
    ],
    integrityRoutes: ["/api/documents/import-signed"],
  }),
] as const;

const BY_ID = new Map(DOCUMENT_REGISTRY.map((d) => [d.id, d]));

export function getDocumentDefinition(id: string): DocumentDefinition | null {
  return BY_ID.get(id) ?? null;
}

export function listActiveDocumentDefinitions(): DocumentDefinition[] {
  return DOCUMENT_REGISTRY.filter((d) => d.active);
}

export function definitionForClinicalType(type: string): DocumentDefinition | null {
  const direct = BY_ID.get(type);
  if (direct) return direct;
  if (type === "form" || type === "residencia") return BY_ID.get("formulario_oficial") ?? null;
  return BY_ID.get("livre") ?? null;
}
